Desafio/Desafio_Web/urls.py
#coding: utf-8
from django.conf.urls import include, url
from django.contrib import admin
from Desafio_Web import settings
from django.views.static import serve

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^media/(.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    url(r'^Desafio/', include('desafio_app.urls', namespace="desafio")),
]

Desafio/desafio_app/urls.py
#coding: utf-8
from django.conf.urls import url


from desafio_app.views.Index import Index
from desafio_app.views.Cadastro_Projeto import cadastro_projeto

from desafio_app.views.Cadastro_Atividades import cadastro_atividades
from desafio_app.views.Andamento_Projeto import andamento_projeto
from desafio_app.views.Andamento_Projeto_Resultado import andamento_projeto_resultado

from desafio_app.views.Status_Projeto import status_projeto
from desafio_app.views.Status_Projeto_Resultado import status_projeto_resultado

from desafio_app.views.Desativar_Projeto import desativar_projeto

from desafio_app.views.Lista_Excluir_Projeto import lista_excluir_projeto

from desafio_app.views.Lista_Excluir_Atividade import lista_excluir_atividade

from desafio_app.views.Desativar_Atividade import desativar_atividade

urlpatterns = [
    url(r'^index/$', Index.as_view(), name='index'),
    url(r'^cadastrar_projeto/$', cadastro_projeto.as_view(), name='Cadastrar_Projeto'),
    url(r'^cadastrar_atividade/$', cadastro_atividades.as_view(), name='Cadastrar_Atividade'),
    url(r'^andamento_projeto/$', andamento_projeto.as_view(), name='Andamento_Projeto'),
    url(r'^status_projeto/$', status_projeto.as_view(), name='Status_Projeto'),
    url(r'^excluir_projeto/$', lista_excluir_projeto.as_view(), name='Lista_Excluir_Projeto'),
    url(r'^lista_excluir_atividade/$', lista_excluir_atividade.as_view(), name='Lista_Excluir_Atividade'),
    url(r'^andamento_projeto_resultado/(?P<id>\d+)/$', andamento_projeto_resultado .as_view(), name='Andamento_Projeto_Resultado'),
    url(r'^status_projeto_resultado/(?P<id>\d+)/$', status_projeto_resultado .as_view(), name='Status_Projeto_Resultado'),
    url(r'^desativar_projeto/(?P<id>\d+)/$', desativar_projeto.as_view(), name='Desativar_Projeto'),
    url(r'^desativar_atividade/(?P<id>\d+)/$', desativar_atividade.as_view(), name='Desativar_Atividade')

]

Desafio/desafio_app/models/Atividades.py
from django.db import models

# Create your models here.

from desafio_app.models import projeto


class atividade(models.Model):

    ID_Projeto = models.ForeignKey(projeto)
    Nome_Atividade = models.CharField(max_length=200,unique=True)
    Data_Inicial = models.DateField()
    Data_Final = models.DateField()
    Finalizado = models.BooleanField(default=False)
    Ativo_Atividade = models.BooleanField(default=True)


    def __str__(self):
        return  self.Nome_Atividade

Desafio/desafio_app/models/Projeto.py
from django.db import models

# Create your models here.

class projeto(models.Model):

    Nome_Projeto  = models.CharField(max_length=200,unique=True)
    Data_Inicial  = models.DateField()
    Data_Final    = models.DateField()
    Ativo         = models.BooleanField(default=True)


    def __str__(self):
        return   self.Nome_Projeto

Desafio/desafio_app/forms/Form_Cadastro_Atividades.py
from django import forms

from desafio_app.models import atividade


class Form_Cadastro_Atividades(forms.ModelForm): # uma funcao com o nome PostForm

    class Meta:
        model = atividade
        fields = ('ID_Projeto','Nome_Atividade', 'Data_Inicial', 'Data_Final','Finalizado')

Desafio/desafio_app/forms/Form_Cadastro_Projeto.py
from django import forms

from desafio_app.models import projeto


class Form_Cadastro_Projeto(forms.ModelForm): # uma funcao com o nome PostForm

    class Meta:
        model = projeto
        fields = ('Nome_Projeto','Data_Inicial','Data_Final')

Desafio/desafio_app/forms/Forms_para_Desativar.py
from django import forms # importando uma funcao do django

from desafio_app.models import projeto


class Form_Desativar_Projeto(forms.ModelForm):

    class Meta:
        model = projeto
        fields = ('Ativo',)

Desafio/desafio_app/forms/Forms_para_Desativar_Atividade.py
from django import forms # importando uma funcao do django


from desafio_app.models import atividade

class Form_Desativar_Atividade(forms.ModelForm):

    class Meta:
        model = atividade
        fields = ('Ativo_Atividade',)

Desafio/desafio_app/views/Andamento_Projeto.py
#coding: utf-8
from django.shortcuts import render,HttpResponseRedirect
from django.views.generic.base import View

from  desafio_app.models import projeto


class andamento_projeto(View):

    template = "Andamento_Projeto.html"


    def get(self, request):
        lista = projeto.objects.filter(Ativo=True)
        return render(request, self.template, {'lista': lista})

Desafio/desafio_app/views/Andamento_Projeto_Resultado.py
#coding: utf-8
from django.views.generic.base import View
from django.shortcuts import render

from  desafio_app.models import projeto
from  desafio_app.models import atividade




class andamento_projeto_resultado(View):

    template = "Andamento_Projeto_Resultado.html"

    def get(self, request,id):
        pro = projeto.objects.get(id=id)
        ati = atividade.objects.filter(ID_Projeto = id)

        counter = 0
        for c in ati:
            counter += 1

        not_finalizado = 0
        yes_finalizado = 0

        for x in ati:
            if(x.Finalizado == False):
                not_finalizado +=1
            else:
                yes_finalizado +=1

        if(yes_finalizado >= 1):
            lista = []
            total =  (yes_finalizado * 100) / counter
            lista = total
            print(lista)

            return render(request, self.template, {'lista': lista})
        else:
            context_dict = 0
            return render(request, self.template, {'context_dict':context_dict})

Desafio/desafio_app/views/Cadastro_Atividades.py
#coding: utf-8
from django.shortcuts import render,HttpResponseRedirect
from django.views.generic.base import View

from desafio_app.forms.Form_Cadastro_Atividades import Form_Cadastro_Atividades


class cadastro_atividades(View):

    template = "Cadastro_Atividades.html"
    template1 = "Cadastro_Sucesso_Atividades.html"
    conteudo = {'form': Form_Cadastro_Atividades()}

    def post(self, request):
        form = Form_Cadastro_Atividades(request.POST)
        if form.is_valid():
            form.save(commit=True)
            print ("entrou")
            self.conteudo.update({'messengerSucess': 'Cadastrado com Sucesso', 'messengerError': ''})
            mensagem = "Cadastrado com sucesso!"
            return render(request, self.template1, {'mensagem':mensagem})
        else:
            print(form.errors)
            return render(request, self.template, {'form': form})
        return render(request, self.template, self.conteudo)

    def get(self, request):
        form = Form_Cadastro_Atividades()
        return render(request, self.template, {'form': form})

Desafio/desafio_app/views/Cadastro_Projeto.py
#coding: utf-8
from django.shortcuts import render,HttpResponseRedirect
from django.views.generic.base import View

from desafio_app.forms.Form_Cadastro_Projeto import Form_Cadastro_Projeto


class cadastro_projeto(View):

    template = "Cadastro_Projeto.html"
    template1 = "Cadastro_Sucesso_Projeto.html"
    conteudo = {'form': Form_Cadastro_Projeto()}

    def post(self, request):

        form = Form_Cadastro_Projeto(request.POST)
        if form.is_valid():
            form.save(commit=True)
            print ("entrou")
            self.conteudo.update({'messengerSucess': 'Cadastrado com Sucesso', 'messengerError': ''})
            mensagem = "Cadastrado com sucesso!"

            return render(request, self.template1, {'mensagem':mensagem})
        else:
            print(form.errors)
            return render(request, self.template, {'form': form})
        return render(request, self.template, self.conteudo)

    def get(self, request):
        form = Form_Cadastro_Projeto()
        return render(request, self.template, {'form': form})

Desafio/desafio_app/views/Desativar_Atividade.py
#coding: utf-8

from django.views.generic.base import View
from django.shortcuts import render,HttpResponseRedirect

from desafio_app.models import atividade

from desafio_app.forms.Forms_para_Desativar_Atividade import Form_Desativar_Atividade


class desativar_atividade(View):
    template = "Excluido_Atividade.html"

    conteudo = {
        'editar': Form_Desativar_Atividade(),
    }


    def get(self, request, id=None):
        if id:

            dependente = atividade.objects.get(pk=id)

            form = Form_Desativar_Atividade(instance=dependente, data=request.POST)
        else:

            id = None
            form = Form_Desativar_Atividade(data=request.POST)

        if form.is_valid():
            form.save()
            self.template = "Excluido_Atividade.html"
            mensagem = 'Eliminado com Sucesso'
            print('Foi excluido')
            return render(request,self.template,{'mensagem':mensagem }) # arrumar aqui
        else:
            print("Nao excluiu")
            print(form.errors)

        return render(request, self.template, {'form': form, 'method': 'post', 'id': id})




    def post(self, request,id=None):
        if request.POST['id']:
            id = request.POST['id']
            dependente = atividade.objects.get(pk=id)
            form =  Form_Desativar_Atividade(instance=dependente, data=request.POST)
        else:
            id = None
            form = Form_Desativar_Atividade(data=request.POST)

        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/Desafio/status_projeto/' + id ) # arrumar aqui
        else:
            print(form.errors)

        return render(request, self.template, {'form': form, 'method': 'post', 'id': id})

Desafio/desafio_app/views/Desativar_Projeto.py
#coding: utf-8

from django.views.generic.base import View
from django.shortcuts import render,HttpResponseRedirect

from desafio_app.models import projeto

from desafio_app.forms.Forms_para_Desativar import Form_Desativar_Projeto


class desativar_projeto(View):
    template = "Excluido_Projeto.html"

    conteudo = {
        'editar': Form_Desativar_Projeto(),
    }


    def get(self, request, id=None):
        if id:

            dependente = projeto.objects.get(pk=id)
            form = Form_Desativar_Projeto(instance=dependente, data=request.POST)
        else:
            id = None
            form = Form_Desativar_Projeto(data=request.POST)

        if form.is_valid():
            form.save()
            self.template = "Excluido_Projetos.html"
            mensagem = 'Eliminado com Sucesso'
            print('Foi excluido')
            return render(request,self.template,{'mensagem':mensagem }) # arrumar aqui
        else:
            print("Nao excluiu")
            print(form.errors)

        return render(request, self.template, {'form': form, 'method': 'post', 'id': id})




    def post(self, request,id=None):
        if request.POST['id']:
            id = request.POST['id']
            dependente = projeto.objects.get(pk=id)
            form =  Form_Desativar_Projeto(instance=dependente, data=request.POST)
        else:
            id = None
            form = Form_Desativar_Projeto(data=request.POST)

        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/Desafio/status_projeto/' + id ) # arrumar aqui
        else:
            print(form.errors)

        return render(request, self.template, {'form': form, 'method': 'post', 'id': id})

Desafio/desafio_app/views/Index.py
#coding: utf-8
from django.views.generic.base import View
from django.shortcuts import render

from desafio_app.models import projeto


class Index(View):

    def get(self, request):

        pro  = projeto.objects.all()
        context_dict = {}
        return render(request, 'Index.html', {'pro':pro})

Desafio/desafio_app/views/Lista_Excluir_Atividade.py
#coding: utf-8
from django.shortcuts import render,HttpResponseRedirect
from django.views.generic.base import View

from  desafio_app.models import atividade


class lista_excluir_atividade(View):

    template = "Lista_Excluir_Atividade.html"


    def get(self, request):
        lista = atividade.objects.filter(Ativo_Atividade=True)
        return render(request, self.template, {'lista': lista})

Desafio/desafio_app/views/Lista_Excluir_Projeto.py
#coding: utf-8
from django.shortcuts import render,HttpResponseRedirect
from django.views.generic.base import View

from  desafio_app.models import projeto


class lista_excluir_projeto(View):

    template = "Lista_Excluir_Projeto.html"


    def get(self, request):
        lista = projeto.objects.filter(Ativo=True)
        return render(request, self.template, {'lista': lista})

Desafio/desafio_app/views/Status_Projeto.py
#coding: utf-8
from django.shortcuts import render,HttpResponseRedirect
from django.views.generic.base import View

from  desafio_app.models import projeto


class status_projeto(View):

    template = "Status_Projeto.html"


    def get(self, request):
        lista = projeto.objects.filter(Ativo=True)
        return render(request, self.template, {'lista': lista})

Desafio/desafio_app/views/Status_Projeto_Resultado.py
#coding: utf-8
from django.views.generic.base import View
from django.shortcuts import render

from  desafio_app.models import projeto
from  desafio_app.models import atividade


class status_projeto_resultado(View):

    template = "Status_Projeto_Resultado.html"

    def get(self, request,id):
        pro = projeto.objects.get(id=id)
        ati = atividade.objects.filter(ID_Projeto = id)


        data_pro = pro.Data_Final

        var = []
        var3 = []
        sem_valor = 2

        if(len(ati) > 0):
            for x in ati:
                data = x.Data_Final
                var.append(data)

                if(data > data_pro ):
                    print('Projeto vai atrasar por causa da atividade', x.Nome_Atividade)
                    if(x.Ativo_Atividade == True):
                        var3.append(x)

                if(len(var3) >= 1):
                    sem_valor = 1

        return render(request, self.template, {'var3': var3,'data_pro':data_pro,'sem_valor':sem_valor})

Desafio/desafio_app/templates/Andamento_Projeto.html
{% extends 'base.html' %}

{% block body %}
{%  include 'Menu_Index.html' %}
{% endblock %}


{% load staticfiles %}

{% block body_block %}

<div class="four wide column centered ">

     <br>
     <h1>Andamento do Projeto</h1>
     <p>Selecione o Projeto:</p>

      <div ui grid>
          {%for c in lista %}

           <div class="extra content">
                <a  href="/Desafio/andamento_projeto_resultado/{{ c.id }}/" > {{ c.Nome_Projeto }}</a>

           </div>


          {%endfor%}

        </div>


{% endblock %}

Desafio/desafio_app/templates/Andamento_Projeto_Resultado.html
{% extends 'base.html' %}

{% block body %}
{%  include 'Menu_Index.html' %}
{% endblock %}


{% load staticfiles %}

{% block body_block %}

<div class="four wide column centered ">

    <br>
     <h2>Andamento do Projeto Resultado</h2>


    {% if lista > 0 %}
    <label for="file"><h1>{{lista}}%<h1></label>
    <progress id="file" value="{{lista}}" max="100"> 32% </progress>
    </div>

    {%else%}

    <label for="file"><h1>0%<h1></label>
    <progress id="file" value="0" max="100"> 32% </progress>
    </div>
     {%endif%}


{% endblock %}

Desafio/desafio_app/templates/Cadastro_Atividades.html
{% extends 'base.html' %}

{% block body %}

{% endblock %}





{% load staticfiles %}



{% block body_block %}

    <div class="four wide column centered inverted">


    <form class="ui form" id="category_form"  method= "post" {% if id %} action="."  {% else %} action="{% url 'desafio:Cadastrar_Atividade' %}"{%endif%}>
        {% csrf_token %}

            <section class="eight wide column"></section>

        <h2>Cadastro de Atividade</h2>

                       <h5>Nome da Atividade</h5>
                        {{ form.Nome_Atividade }}
                        {{form.Nome_Projeto.errors}}

                         <h5>Projeto</h5>
                        {{ form.ID_Projeto }}
                        {{form.ID_Projeto.errors}}

                        <h5>Data inicial</h5>
                        {{ form.Data_Inicial }}
                        {{form.modelo.errors}}

                          <h5>Data Final</h5>
                        {{ form.Data_Final }}
                        {{form.Data_Final.errors}}

                        <h5>Finalizado</h5>
                        {{ form.Finalizado }}
                        {{form.Finalizado.errors}}

                        <br>
                        <input name="id" type="hidden" value="{{id_post}}"/>
                        {% if field.errors %}
                        <br>
                            <div id="error" class="ui pointing label top red basic erro">
                                {{ field.errors }}
                            </div>
                        {% endif %}

<br>
 {%if id%}

        <div class="sixteen wide column">
            <button type="submit" class="ui button" name="submit">Salvar</button>
        </div>
{%else%}
        <div class="sixteen wide column">
            <a class="ui red button"  href="/Desafio/index">Voltar</a>
            <button type="submit" class="ui green button" name="submit">Salvar</button>
        </div>
        {%endif%}

    </form>
    </div>

{% endblock %}

Desafio/desafio_app/templates/Cadastro_Sucesso.html
{% extends 'base.html' %}

{% block body %}
{%  include 'Menu_Index.html' %}
{% endblock %}


{% load staticfiles %}

{% block body_block %}

<div class="three wide column centered ">

    <div class="id1"></div>
    <div ui grid>

        <div class="ui positive message">

          <div class="header">
            {{mensagem}}
          </div>
        </div>

         <div ui grid>
          <a class="ui red button"  href="/Desafio/index">Voltar</a>
           </div>


</div>


{% endblock %}

Desafio/desafio_app/templates/Cadastro_Sucesso_Atividades.html
{% extends 'base.html' %}

{% block body %}
{%  include 'Menu_Index.html' %}
{% endblock %}


{% load staticfiles %}

{% block body_block %}

<div class="three wide column centered ">

    <div class="id1"></div>
    <br>

    <div ui grid>

        <div class="ui positive message">

          <div class="header">
            {{mensagem}}
          </div>
        </div>

         <div ui grid>
          <a class="ui red button"  href="/Desafio/cadastrar_atividade">Voltar</a>
           </div>


</div>


{% endblock %}

Desafio/desafio_app/templates/Cadastro_Sucesso_Projeto.html
{% extends 'base.html' %}

{% block body %}
{%  include 'Menu_Index.html' %}
{% endblock %}


{% load staticfiles %}

{% block body_block %}

<div class="three wide column centered ">

    <div class="id1"></div>
    <br>

    <div ui grid>

        <div class="ui positive message">

          <div class="header">
            {{mensagem}}
          </div>
        </div>

         <div ui grid>
          <a class="ui red button"  href="/Desafio/cadastrar_projeto">Voltar</a>
           </div>


</div>


{% endblock %}

Desafio/desafio_app/templates/Excluido_Atividade.html
{% extends 'base.html' %}

{% block body %}
{%  include 'Menu_Index.html' %}
{% endblock %}


{% load staticfiles %}

{% block body_block %}

<div class="three wide column centered ">

    <div class="id1"></div>

    <div ui grid>

        <div class="ui positive message">

          <div class="header">
            {{mensagem}}
          </div>
        </div>

         <div ui grid>
          <a class="ui red button"  href="/Desafio/lista_excluir_atividade">Voltar</a>
           </div>


</div>


{% endblock %}

Desafio/desafio_app/templates/Excluido_Projetos.html
{% extends 'base.html' %}

{% block body %}
{%  include 'Menu_Index.html' %}
{% endblock %}


{% load staticfiles %}

{% block body_block %}

<div class="three wide column centered ">

    <div class="id1"></div>
    <div ui grid>

        <div class="ui positive message">

          <div class="header">
            {{mensagem}}
          </div>
        </div>

         <div ui grid>
          <a class="ui red button"  href="/Desafio/index">Voltar</a>
           </div>


</div>


{% endblock %}

Desafio/desafio_app/templates/Index.html
{% extends 'base.html' %}

{% block body %}
{%  include 'Menu_Index.html' %}
{% endblock %}


{% load staticfiles %}

{% block body_block %}


<div class="two wide column centered ">

 <div class="id1"></div>
      <div ui grid>

            <button class="ui button">
                 <a class="item" href="{% url 'desafio:Andamento_Projeto' %}">Andamento dos Projetos</a>
</button>
           </div>

<div class="id"></div>

      <div ui grid>
           <button class="ui button">
                 <a class="item" href="{% url 'desafio:Status_Projeto' %}">Status dos Projeto</a>
          </button>
           </div>

 </div>
</div>


{% endblock %}

Desafio/desafio_app/templates/Lista_Excluir_Atividade.html
{% extends 'base.html' %}

{% block body %}
{%  include 'Menu_Index.html' %}
{% endblock %}


{% load staticfiles %}

{% block body_block %}

<div class="three wide column centered ">

     <h1>Eliminar Atividade</h1>
     <p>Selecione Atividade:</p>

    <div ui grid>
          {%for c in lista %}

           <div class="extra content">

                 <a  href="/Desafio/desativar_atividade/{{ c.id }}/" > {{ c.Nome_Atividade }} </a>

          </div>

          {%endfor%}

</div>


{% endblock %}

Desafio/desafio_app/templates/Lista_Excluir_Projeto.html
{% extends 'base.html' %}

{% block body %}
{%  include 'Menu_Index.html' %}
{% endblock %}


{% load staticfiles %}

{% block body_block %}

<div class="three wide column centered ">
    <br>
     <h1>Eliminar Projeto</h1>
     <p>Selecione o projeto:</p>

    <div ui grid>
          {%for c in lista %}

           <div class="extra content">

                 <a  href="/Desafio/desativar_projeto/{{ c.id }}/" > {{ c.Nome_Projeto }} </a>

          </div>

          {%endfor%}

</div>


{% endblock %}

Desafio/desafio_app/templates/Status_Projeto.html
{% extends 'base.html' %}

{% block body %}
{%  include 'Menu_Index.html' %}
{% endblock %}


{% load staticfiles %}

{% block body_block %}

<div class="three wide column centered ">
    <br>
     <h1>Status do Projeto</h1>
     <p>Selecione o projeto:</p>

    <div ui grid>
          {%for c in lista %}

           <div class="extra content">
                <a> <a  href="/Desafio/status_projeto_resultado/{{ c.id }}/" > {{ c.Nome_Projeto }}</a>


          </div>

          {%endfor%}

</div>


{% endblock %}

Desafio/desafio_app/templates/Status_Projeto_Resultado.html
{% extends 'base.html' %}

{% block body %}
{%  include 'Menu_Index.html' %}
{% endblock %}


{% load staticfiles %}

{% block body_block %}


<div class="four wide column centered ">
<h1>Status do Projeto Resultado</h1>



       <div ui grid>

       {%for c in var3 %}

       <p> O Projeto vai atrasar por causa da Atividade: {{ c }} Data: {{c.Data_Final}} <p><br>

    {%endfor%}

     {% if sem_valor == 2%}
      <p>O Projeto não vai atrasar!<p>

           {% else %}
        <i>O Projeto esta com a data final para o dia: {{data_pro}}<i>
    {% endif %}


     </div>
</div>
{% endblock %}

Desafio/desafio_app/templates/base.html
{% load staticfiles %}

<html xml:lang="pt" lang="br">

<head>
	<title> {% block title %} Desafio Web {% endblock %}</title>
	<meta http-equiv="content-type" content="text/html;charset=utf-8" />
    <link rel="stylesheet" type="text/css" href="{% static 'semantic/semantic.min.css' %}">
    <script src="{% static 'semantic/semantic.min.js' %}"></script>
    <script src="{% static 'semantic/semantic.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'desafio.css' %}"/>

</head>

<body>
	<header class="topo ui grid">
        <div ui grid>
            <div class="two wide column">

            </div>
        </div>
        <div ui grid>
            <div class="two wide column">

        </div>
        </div>
    </header>


    <nav class="ui seconsdary pointing menu">
            {% block body %}{% endblock %}
    </nav>

     <article class="ui grid conteudo">
        {% block body_block %}

        {% endblock %}
    </article>

    <footer class="ui grid footer">
        <div class="two wide column">
            <a href="https://www.facebook.com/"><i class="large facebook icon"></i></a>
            <a href="https://www.instagram.com/"><i class="large instagram icon"></i></a>
        </div>

        <div  class="twelve wide column">
            <p> Processo Seletivo Grupo Euax - Desafio Web Developer</p><br>
            <br>
        </div>
        </div>


    </footer>



</body>
</html>